spring:
  application:
    name: MessageManager
  data:
    mongodb:
      host: localhost
      port: 27017
      database: messenger-message
server:
  port: 0
clients:
  filemanager:
    url: http://localhost:8765/filemanager
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5