server:
  port: 8090

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/messenger
    
  jpa:
    hibernate:
      ddl-auto: update