spring:
  application:
    name: MessageManager
  data:
    mongodb:
      host: localhost
      port: 27017
      database: messenger-message
server:
  port: 0
clients:
  filemanager:
    url: http://localhost:8765/filemanager