info:
  component: ZuulServer
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
server:
  port: 8765
spring:
  application:
    name: Zuul Server
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000 