spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 128KB
  application:
    name: FileManager
server:
  port: 0
storage:
  location: D:\workspace\messenger-storage
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5