spring:
  application:
    name: User management
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/messenger_user_db
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
server:
  port: 0
